// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRIANGLESERIALIZATIONSCHEMA_ENGINE_H_
#define FLATBUFFERS_GENERATED_TRIANGLESERIALIZATIONSCHEMA_ENGINE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Engine {

struct Vec2;

struct Vec3;

struct Vec4;

struct IVec2;

struct MeshVertex;

struct Triangle;

struct FloatRow;
struct FloatRowBuilder;

struct TerrainMeshData;
struct TerrainMeshDataBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) IVec2 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;

 public:
  IVec2()
      : x_(0),
        y_(0) {
  }
  IVec2(int32_t _x, int32_t _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  int32_t x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(IVec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MeshVertex FLATBUFFERS_FINAL_CLASS {
 private:
  Engine::Vec4 position_;
  Engine::Vec3 normal_;
  Engine::Vec2 texCoords_;
  Engine::Vec3 tangent_;
  Engine::Vec3 bitangent_;

 public:
  MeshVertex()
      : position_(),
        normal_(),
        texCoords_(),
        tangent_(),
        bitangent_() {
  }
  MeshVertex(const Engine::Vec4 &_position, const Engine::Vec3 &_normal, const Engine::Vec2 &_texCoords, const Engine::Vec3 &_tangent, const Engine::Vec3 &_bitangent)
      : position_(_position),
        normal_(_normal),
        texCoords_(_texCoords),
        tangent_(_tangent),
        bitangent_(_bitangent) {
  }
  const Engine::Vec4 &position() const {
    return position_;
  }
  const Engine::Vec3 &normal() const {
    return normal_;
  }
  const Engine::Vec2 &texCoords() const {
    return texCoords_;
  }
  const Engine::Vec3 &tangent() const {
    return tangent_;
  }
  const Engine::Vec3 &bitangent() const {
    return bitangent_;
  }
};
FLATBUFFERS_STRUCT_END(MeshVertex, 60);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Triangle FLATBUFFERS_FINAL_CLASS {
 private:
  Engine::Vec3 vertices_[3];
  uint32_t indices_[3];

 public:
  Triangle()
      : vertices_(),
        indices_() {
  }
  Triangle(::flatbuffers::span<const Engine::Vec3, 3> _vertices, ::flatbuffers::span<const uint32_t, 3> _indices) {
    ::flatbuffers::CastToArray(vertices_).CopyFromSpan(_vertices);
    ::flatbuffers::CastToArray(indices_).CopyFromSpan(_indices);
  }
  const ::flatbuffers::Array<Engine::Vec3, 3> *vertices() const {
    return &::flatbuffers::CastToArray(vertices_);
  }
  const ::flatbuffers::Array<uint32_t, 3> *indices() const {
    return &::flatbuffers::CastToArray(indices_);
  }
};
FLATBUFFERS_STRUCT_END(Triangle, 48);

struct FloatRow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FloatRowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<float> *values() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct FloatRowBuilder {
  typedef FloatRow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<float>> values) {
    fbb_.AddOffset(FloatRow::VT_VALUES, values);
  }
  explicit FloatRowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FloatRow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FloatRow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FloatRow> CreateFloatRow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> values = 0) {
  FloatRowBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FloatRow> CreateFloatRowDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<float>(*values) : 0;
  return Engine::CreateFloatRow(
      _fbb,
      values__);
}

struct TerrainMeshData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TerrainMeshDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MINX = 4,
    VT_MINZ = 6,
    VT_MAXX = 8,
    VT_MAXZ = 10,
    VT_GRIDCOORDS = 12,
    VT_CURRENTSEED = 14,
    VT_MESHVERTICES = 16,
    VT_INDICES = 18,
    VT_HEIGHTMAP2D = 20,
    VT_NORMALHEIGHTMAP = 22,
    VT_TRIANGLES = 24,
    VT_MINHEIGHT = 26,
    VT_MAXHEIGHT = 28
  };
  int32_t minX() const {
    return GetField<int32_t>(VT_MINX, 0);
  }
  int32_t minZ() const {
    return GetField<int32_t>(VT_MINZ, 0);
  }
  int32_t maxX() const {
    return GetField<int32_t>(VT_MAXX, 0);
  }
  int32_t maxZ() const {
    return GetField<int32_t>(VT_MAXZ, 0);
  }
  const Engine::IVec2 *gridCoords() const {
    return GetStruct<const Engine::IVec2 *>(VT_GRIDCOORDS);
  }
  uint32_t currentSeed() const {
    return GetField<uint32_t>(VT_CURRENTSEED, 0);
  }
  const ::flatbuffers::Vector<const Engine::MeshVertex *> *meshVertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Engine::MeshVertex *> *>(VT_MESHVERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Engine::FloatRow>> *heightMap2D() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Engine::FloatRow>> *>(VT_HEIGHTMAP2D);
  }
  const ::flatbuffers::Vector<float> *normalHeightMap() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_NORMALHEIGHTMAP);
  }
  const ::flatbuffers::Vector<const Engine::Triangle *> *triangles() const {
    return GetPointer<const ::flatbuffers::Vector<const Engine::Triangle *> *>(VT_TRIANGLES);
  }
  float minHeight() const {
    return GetField<float>(VT_MINHEIGHT, 0.0f);
  }
  float maxHeight() const {
    return GetField<float>(VT_MAXHEIGHT, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MINX, 4) &&
           VerifyField<int32_t>(verifier, VT_MINZ, 4) &&
           VerifyField<int32_t>(verifier, VT_MAXX, 4) &&
           VerifyField<int32_t>(verifier, VT_MAXZ, 4) &&
           VerifyField<Engine::IVec2>(verifier, VT_GRIDCOORDS, 4) &&
           VerifyField<uint32_t>(verifier, VT_CURRENTSEED, 4) &&
           VerifyOffset(verifier, VT_MESHVERTICES) &&
           verifier.VerifyVector(meshVertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyOffset(verifier, VT_HEIGHTMAP2D) &&
           verifier.VerifyVector(heightMap2D()) &&
           verifier.VerifyVectorOfTables(heightMap2D()) &&
           VerifyOffset(verifier, VT_NORMALHEIGHTMAP) &&
           verifier.VerifyVector(normalHeightMap()) &&
           VerifyOffset(verifier, VT_TRIANGLES) &&
           verifier.VerifyVector(triangles()) &&
           VerifyField<float>(verifier, VT_MINHEIGHT, 4) &&
           VerifyField<float>(verifier, VT_MAXHEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct TerrainMeshDataBuilder {
  typedef TerrainMeshData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_minX(int32_t minX) {
    fbb_.AddElement<int32_t>(TerrainMeshData::VT_MINX, minX, 0);
  }
  void add_minZ(int32_t minZ) {
    fbb_.AddElement<int32_t>(TerrainMeshData::VT_MINZ, minZ, 0);
  }
  void add_maxX(int32_t maxX) {
    fbb_.AddElement<int32_t>(TerrainMeshData::VT_MAXX, maxX, 0);
  }
  void add_maxZ(int32_t maxZ) {
    fbb_.AddElement<int32_t>(TerrainMeshData::VT_MAXZ, maxZ, 0);
  }
  void add_gridCoords(const Engine::IVec2 *gridCoords) {
    fbb_.AddStruct(TerrainMeshData::VT_GRIDCOORDS, gridCoords);
  }
  void add_currentSeed(uint32_t currentSeed) {
    fbb_.AddElement<uint32_t>(TerrainMeshData::VT_CURRENTSEED, currentSeed, 0);
  }
  void add_meshVertices(::flatbuffers::Offset<::flatbuffers::Vector<const Engine::MeshVertex *>> meshVertices) {
    fbb_.AddOffset(TerrainMeshData::VT_MESHVERTICES, meshVertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(TerrainMeshData::VT_INDICES, indices);
  }
  void add_heightMap2D(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Engine::FloatRow>>> heightMap2D) {
    fbb_.AddOffset(TerrainMeshData::VT_HEIGHTMAP2D, heightMap2D);
  }
  void add_normalHeightMap(::flatbuffers::Offset<::flatbuffers::Vector<float>> normalHeightMap) {
    fbb_.AddOffset(TerrainMeshData::VT_NORMALHEIGHTMAP, normalHeightMap);
  }
  void add_triangles(::flatbuffers::Offset<::flatbuffers::Vector<const Engine::Triangle *>> triangles) {
    fbb_.AddOffset(TerrainMeshData::VT_TRIANGLES, triangles);
  }
  void add_minHeight(float minHeight) {
    fbb_.AddElement<float>(TerrainMeshData::VT_MINHEIGHT, minHeight, 0.0f);
  }
  void add_maxHeight(float maxHeight) {
    fbb_.AddElement<float>(TerrainMeshData::VT_MAXHEIGHT, maxHeight, 0.0f);
  }
  explicit TerrainMeshDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TerrainMeshData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TerrainMeshData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TerrainMeshData> CreateTerrainMeshData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t minX = 0,
    int32_t minZ = 0,
    int32_t maxX = 0,
    int32_t maxZ = 0,
    const Engine::IVec2 *gridCoords = nullptr,
    uint32_t currentSeed = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Engine::MeshVertex *>> meshVertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Engine::FloatRow>>> heightMap2D = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> normalHeightMap = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Engine::Triangle *>> triangles = 0,
    float minHeight = 0.0f,
    float maxHeight = 0.0f) {
  TerrainMeshDataBuilder builder_(_fbb);
  builder_.add_maxHeight(maxHeight);
  builder_.add_minHeight(minHeight);
  builder_.add_triangles(triangles);
  builder_.add_normalHeightMap(normalHeightMap);
  builder_.add_heightMap2D(heightMap2D);
  builder_.add_indices(indices);
  builder_.add_meshVertices(meshVertices);
  builder_.add_currentSeed(currentSeed);
  builder_.add_gridCoords(gridCoords);
  builder_.add_maxZ(maxZ);
  builder_.add_maxX(maxX);
  builder_.add_minZ(minZ);
  builder_.add_minX(minX);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TerrainMeshData> CreateTerrainMeshDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t minX = 0,
    int32_t minZ = 0,
    int32_t maxX = 0,
    int32_t maxZ = 0,
    const Engine::IVec2 *gridCoords = nullptr,
    uint32_t currentSeed = 0,
    const std::vector<Engine::MeshVertex> *meshVertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr,
    const std::vector<::flatbuffers::Offset<Engine::FloatRow>> *heightMap2D = nullptr,
    const std::vector<float> *normalHeightMap = nullptr,
    const std::vector<Engine::Triangle> *triangles = nullptr,
    float minHeight = 0.0f,
    float maxHeight = 0.0f) {
  auto meshVertices__ = meshVertices ? _fbb.CreateVectorOfStructs<Engine::MeshVertex>(*meshVertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  auto heightMap2D__ = heightMap2D ? _fbb.CreateVector<::flatbuffers::Offset<Engine::FloatRow>>(*heightMap2D) : 0;
  auto normalHeightMap__ = normalHeightMap ? _fbb.CreateVector<float>(*normalHeightMap) : 0;
  auto triangles__ = triangles ? _fbb.CreateVectorOfStructs<Engine::Triangle>(*triangles) : 0;
  return Engine::CreateTerrainMeshData(
      _fbb,
      minX,
      minZ,
      maxX,
      maxZ,
      gridCoords,
      currentSeed,
      meshVertices__,
      indices__,
      heightMap2D__,
      normalHeightMap__,
      triangles__,
      minHeight,
      maxHeight);
}

inline const Engine::TerrainMeshData *GetTerrainMeshData(const void *buf) {
  return ::flatbuffers::GetRoot<Engine::TerrainMeshData>(buf);
}

inline const Engine::TerrainMeshData *GetSizePrefixedTerrainMeshData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Engine::TerrainMeshData>(buf);
}

template <bool B = false>
inline bool VerifyTerrainMeshDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Engine::TerrainMeshData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedTerrainMeshDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Engine::TerrainMeshData>(nullptr);
}

inline void FinishTerrainMeshDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Engine::TerrainMeshData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTerrainMeshDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Engine::TerrainMeshData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Engine

#endif  // FLATBUFFERS_GENERATED_TRIANGLESERIALIZATIONSCHEMA_ENGINE_H_
